SELECT INSERT('Hello Bobby', 6, 0, ' There');
SELECT INSERT('Hello Bobby', 6, 4, ' There');
SELECT INSERT('Hello Bobby', 6, 6, ' There');
SELECT RIGHT('omghahalol!', 4);
SELECT LEFT('omghahalol!', 3);
SELECT REPEAT('ha', 4);
SELECT TRIM ('   pickle   ');
SELECT TRIM(LEADING '.' FROM '....San Antonio...');
SELECT TRIM(TRAILING '.' FROM '....San Antonio...');
SELECT TRIM(BOTH '.' FROM '....San Antonio...');
